import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { Provider } from "react-redux";
import store from "./store";
import Entry from "./entry";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>React Redux 2022 Official</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Welcome to React Redux!</h1>

      <Provider store={store}>
        <Entry />
      </Provider>
    </div>
  );
};

export default Home;
